techpack/display: renamed trace events to not collide with built in symbols.
Resolved error:

ld.lld: error: duplicate symbol: __traceiter_tracing_mark_write
>>> defined in kernel/built-in.a(trace/trace_tracing_mark_write.o)
>>> defined in techpack/built-in.a(display/msm/sde/sde_kms.o)

ld.lld: error: duplicate symbol: ts
>>> defined in techpack/built-in.a(touch/nt36xxx/nt36xxx.o)
>>> defined in techpack/built-in.a(touch/raydium/drv_interface.o)

ld.lld: error: duplicate symbol: __SCK__tp_func_tracing_mark_write
>>> defined in kernel/built-in.a(trace/trace_tracing_mark_write.o)
>>> defined in techpack/built-in.a(display/msm/sde/sde_kms.o)

ld.lld: error: duplicate symbol: __tracepoint_tracing_mark_write
>>> defined in kernel/built-in.a(trace/trace_tracing_mark_write.o)
>>> defined in techpack/built-in.a(display/msm/sde/sde_kms.o)

Signed-off-by: AKM <akmabrar04@gmail.com>